name: floating_promo_video
description: A Flutter package for draggable floating promo videos with Instagram token support and direct URL playback.
version: 1.0.0
homepage: https://github.com/deeps00007/floating_promo_video
repository: https://github.com/deeps00007/floating_promo_video
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.7.0
  chewie: ^1.5.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.1.0

flutter:
  uses-material-design: true