name: floating_promo_video
description: A Flutter package for draggable floating promo videos with Instagram token support and direct URL playback.
version: 1.0.0
homepage: https://github.com/deeps00007/floating_promo_video
repository: https://github.com/deeps00007/floating_promo_video
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.2.0
  chewie: ^1.2.2
  http: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  build_runner: ^2.0.0
  build_web_compilers: ^3.2.0
flutter:
  plugin:
    platforms:
      android:
        package: floating_promo_video
        pluginClass: FloatingPromoVideoPlugin
      ios:
        pluginClass: FloatingPromoVideoPlugin
      web:
        pluginClass: FloatingPromoVideoPlugin
        fileName: floating_promo_video_web.dart